[package]
name = "hands_on_project_one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

git2 = "0.17.2"
open = "5.0.0"
webbrowser = "0.8.10"


